### Cadastro de usuário 
POST http://localhost:3003/signup
Content-Type: application/json

{
    "name":"",
    "email":"",
    "password":"",
    "role":""
}

### Login
POST http://localhost:3003/login
Content-Type: application/json

{
    "email":"felipe@gmail.com",
    "password":"fe123"
}

### Pegar informações do próprio perfil
GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: 

### Pegar informações do perfil de outro usuário 
GET http://localhost:3003/user/:id
Content-Type: application/json
Authorization: 

### Pegar informações de todos os usuário 
GET http://localhost:3003/allusers
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUzMDEwNzY0LWEwYTAtNDA1Yy04YTc1LTE2MjhlNzYyY2Q5YSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY0NjI0MDg4NSwiZXhwIjoxNjQ2MzI3Mjg1fQ.v3orOIjCLOnBGBcFV52rWxWVbfDTjq9f5Per3ivwHzM

### Criando receita
POST http://localhost:3003/recipe
Content-Type: application/json
Authorization: 

{
    "title": "",
    "description": "",
    "recipe_img":""
}

### Pegar informações da receita
GET http://localhost:3003/recipe/:id
Content-Type: application/json
Authorization: 

### Pegar informações de todas as receita
GET http://localhost:3003/allrecipes
Content-Type: application/json
Authorization: 

### Seguir usuário
POST http://localhost:3003/user/follow
Content-Type: application/json
Authorization: 

{
    "userToFollowId":""
}

### Deixar de seguir usuário
DELETE http://localhost:3003/user/unfollow
Content-Type: application/json
Authorization: 

{
    "userToUnfollowId":""
}

### Pegar feed de receitas
GET http://localhost:3003/user/feed
Content-Type: application/json
Authorization: 

### Editar receita
PUT http://localhost:3003/recipe/:id/edit
Content-Type: application/json
Authorization: 

{
    "title":"",
    "description": "",
    "recipe_img":""
}

### Deletar receita
DELETE http://localhost:3003/recipe/:id/delete
Content-Type: application/json
Authorization: 

### Deletar usuário
DELETE http://localhost:3003/user/:id/delete
Content-Type: application/json
Authorization:

### Esqueceu sua senha
PUT http://localhost:3003/newPassword
Content-Type: application/json

{
    "email": "leozbroca@gmail.com"
}
